### ISSUE TITLE
Something about review the work

### ISSUE THREAD

**Issue by zhanghengjing2** [dee-ex/aicovidvn115m#1]
Hi! Thank you for your data and methods! But when I run the code, I can not get the same result. In train, the  train's auc: 0.913879   valid's auc: 0.632. Is this correct？

**Comment by binhfdv** [comment]
Hi guy!
Thanks for your feedback, could you give us the information about your training environment?
As mentioned in the repo, the solution was trained on Google Colab (basic).
We also trained and tested the model thousands of times to make sure the result is stable and true. (because we attended a competition)
We feel free to help solve any issues about the repo.
Regards.

**Comment by zhanghengjing2** [comment]
> Hi guy!
> Thanks for your feedback, could you give us the information about your training environment?
> As mentioned in the repo, the solution was trained on Google Colab (basic).
> We also trained and tested the model thousands of times to make sure the result is stable and true. (because we attended a competition)
> We feel free to help solve any issues about the repo.
> Regards.

Thank you! I think there should be a difference in the data used. I used the official raw data (aicv115m_public_train/metadata_train_challenge.csv) of the aicovidvn 115m. 
Now, I am trying the data you provided (data/train.csv). Would you tell me what preprocessing did you do to the data?

**Comment by dee-ex** [comment]
We have already explained the detail in `report/report.(docx, pdf)` (note that these files are in Vietnamese).  if you have some trouble with reading Vietnamese, here is the English explanation:
In raw data a.k.a `aicv115m_public_train/`, we filter audio which has `audio_noise_note` is NaN (empty) by using metadata file.
Along with that, we also filtered out 21 audio files labeled as 1 (positive) in folder extra data (`aicv115m_extra_public_1235samples/`) also by using metadata file.
However, there are a few missing audio files from the 21 audio files above, which left us 20 files available. Those files are put in the `data/extra/` folder.
And finally, we have a total of 4,068 audio files whose paths and labels are saved in `data/train.csv`. You can notice that in the 20 last rows, those paths are started with `extra/`.

**Comment by zhanghengjing2** [comment]
Thank you very much for your patient explanation! Due to overseas network visits, I did not have the opportunity to participate in this competition. My data is obtained from [here](https://github.com/vnyennhi/AICovidVN-115M), but this data is different from yours, so I am missing many features. 
Now I am using this method to test the Indian data set([Cowsara](https://github.com/iiscleap/Coswara-Data)),I don’t know how the results of the test are

**Comment by binhfdv** [comment]
FYI: the competition consists of 2 stages (`warm-up` and `final`)
So that our data is from the second stage (`final`), and the referenced repo [link](https://github.com/vnyennhi/AICovidVN-115M) you mentioned above is from the first stage.
Since this is a contest, we don't know the true labels of the private test set, either.
